---
title: "Mapping to UKBioBank"
author: "JBF"
date: '`r Sys.time()`'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flextable)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(purrr)
# library(umap)
library(uwot)
library(gridExtra)
library(ClusterR)
library(splines)

# library(dbscan)

remove_outliers <- function(x){
  m <- mean(x, na.rm = TRUE)
  s <- sd(x, na.rm = TRUE)
  upperbound <- m + (5*s)
  lowerbound <- m - (5*s)
  ifelse((x > lowerbound) & (x < upperbound), x, NaN)
}

bbdd_umap <- bbdd_covar %>% 
  mutate(sex = if_else(sex_female == 1, 'Female', 'Male'),
         WHR = if_else(sex_female == 1,
                       if_else(obesity == 1 | 30 <= BMI, 0.9, 0.8),
                       if_else(obesity == 1 | 30 <= BMI, 1, 0.9)),
         CRP = if_else(20 < CRP, as.numeric(NA), CRP)) %>% 
  select(eid = rowId,
         age,
         sex,
         bmi = BMI,
         whr = WHR,
         sbp = SBP,
         dbp = DBP,
         alt = ALT,
         scr =  Creatinine,
         crp = CRP,
         hdl = cHDL,
         tg = Tg,
         ldl = cLDL,
         fg = Glucose,
         smoking = Current) %>%
  ## Removing outliers for all variables (except age)
  mutate(across(-c(eid, sex, age), remove_outliers))
```

# Description
```{r}
bbdd_umap %>%
  summarise(name = 'total',
           N = as.character(n()),
           resum = '') %>%
  bind_rows(bbdd_umap %>%
              select(eid, sex, smoking) %>%
              mutate(smoking = as.character(smoking)) %>% 
              pivot_longer(cols = !eid) %>%
              group_by(name, value) %>%
              summarise(N = n(),
                        .groups = 'keep') %>%
              transmute(name,
                        value,
                        resum = sprintf('%i (%2.1f%%)', N, N/dim(bbdd_covar)[1]* 100))) %>% 
  bind_rows(bbdd_umap %>%
              select(-sex, -smoking) %>% 
              pivot_longer(cols = !eid) %>%
              group_by(name) %>%
              summarise(N = sum(!is.na(value)),
                        mn = mean(value, na.rm = T),
                        sd = sd(value, na.rm = T)) %>%
              transmute(name, 
                        N = sprintf('%i (%2.1f%%)', N, N/dim(bbdd_covar)[1]* 100),
                        resum = sprintf('%2.1f (%2.1f)', mn, sd))) %>%
  select(name, value, N, resum) %>%
  flextable
```

## Only Case-complet
```{r}
recoded_dat <- bbdd_umap %>%
  ## Only complete cases
  drop_na

recoded_dat %>%
  summarise(name = 'total',
           N = as.character(n()),
           resum = '') %>%
  bind_rows(recoded_dat %>%
              select(eid, sex, smoking) %>%
              mutate(smoking = as.character(smoking)) %>% 
              pivot_longer(cols = !eid) %>%
              group_by(name, value) %>%
              summarise(N = n(),
                        .groups = 'keep') %>%
              transmute(name,
                        value,
                        resum = sprintf('%i (%2.1f%%)', N, N/dim(bbdd_covar)[1]* 100))) %>% 
  bind_rows(recoded_dat %>%
              select(-sex, -smoking) %>% 
              pivot_longer(cols = !eid) %>%
              group_by(name) %>%
              summarise(N = sum(!is.na(value)),
                        mn = mean(value, na.rm = T),
                        sd = sd(value, na.rm = T)) %>%
              transmute(name, 
                        N = sprintf('%i (%2.1f%%)', N, N/dim(bbdd_covar)[1]* 100),
                        resum = sprintf('%2.1f (%2.1f)', mn, sd))) %>%
  select(name, value, N, resum) %>%
  flextable
```
## Distributions
```{r, fig.width=20, fig.height=5}
recoded_dat %>%
    pivot_longer(-c(eid, sex)) %>%
    mutate(name = toupper(name)) %>%
    ggplot(aes(value)) +
    geom_histogram(bins = 50) +
    facet_grid(sex ~ name, scales = "free_x") +
    theme_bw()
```

## Corretions
```{r, fig.width=18, fig.height=9}
recoded_dat %>%
    group_by(sex) %>%
    group_modify(~{
        .x %>%
            select(-eid) %>%
            cor %>%
            reshape2::melt()
    }) %>%
    mutate(rsq = value^2, 
           to_mark = ifelse(Var1 != Var2 & rsq > .25, "*", NA),
           across(c(Var1, Var2), toupper)) %>%
    ggplot(aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = to_mark), na.rm = TRUE) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1)) +
    theme_minimal() +
    facet_wrap(~sex, nrow = 1) +
    labs(x = NULL, y = NULL, fill = "Correlation", caption = "* Squared correlation higher than 0.25")
```

# Stratification by sex and transformation
```{r}
strat_dat <- recoded_dat %>%
  split(f = .$sex) %>%
  map(~{.x %>%
      names %>%
      setdiff(c("eid", "sex", "age", "smoking", "bmi")) %>%
      map_dfc(function(feature){
        paste(feature, "~ age + smoking + bmi") %>%
          lm(data = .x) %>%
          resid %>%
          scale %>%
          data.frame %>%
          setNames(feature)
      }) %>%
      mutate(eid = .x$eid, .before = 1)
  })
```

## Distribution
```{r, fig.width=20, fig.height=5}
strat_dat %>%
    bind_rows(.id = "sex") %>%
    pivot_longer(-c(eid, sex)) %>%
    mutate(name = toupper(name)) %>%
    ggplot(aes(value)) +
    geom_histogram(bins = 50) +
    facet_grid(sex ~ name, scales = "free_x")
```

## Corretions
```{r, fig.width=18, fig.height=9}
strat_dat %>%
  map_dfr(~{.x %>%
      select(-eid) %>%
      cor %>%
      reshape2::melt()
  }, .id = "sex") %>%
  mutate(rsq = value^2, 
         to_mark = ifelse(Var1 != Var2 & rsq > .25, "*", NA),
         across(c(Var1, Var2), toupper)) %>%
  ggplot(aes(Var1, Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = to_mark), na.rm = TRUE) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1)) +
  theme_minimal() +
  facet_wrap(~sex, nrow = 1) +
  labs(x = NULL, y = NULL, fill = "Correlation", caption = "* Squared correlation higher than 0.25")
```

# Map to UKBioBank
```{r}
umap_embed <- strat_dat %>%
  map2(umap_res, ~{
    dat1 <- tibble(eid = .x$eid)
    dat2 <- data.frame(umap_transform(X = .x %>% select(-eid),
                                      model = .y))
    bind_cols(dat1, dat2)
  })

umap_embed %>%
  bind_rows(.id = "sex") %>%
  ggplot(aes(X1, X2)) +
  geom_point() +
  facet_wrap(~sex, nrow = 1) +
  theme_bw() +
  labs(x = "UMAP1", y = "UMAP2")

umap_embed %>%
    bind_rows(.id = "sex") %>%
    ggplot(aes(X1, X2)) +
    geom_density_2d_filled() +
    facet_wrap(~sex, nrow = 1) +
    theme_bw() +
    theme(legend.position = "none") +
    labs(x = "UMAP1", y = "UMAP2")
```

## Overlaying input variables
```{r, fig.width=9, fig.height=12}
umap_embed %>%
  bind_rows(.id = "sex") %>%
  {
    d <- recoded_dat %>% 
      select(eid, sex, age, bmi)
    inner_join(., d, by = c("eid", "sex"))
  } %>%
  pivot_longer(c(age, bmi)) %>%
  split(f = .$name) %>%
  imap(~{
    mp <- median(.x$value)
    .x %>%
      ggplot(aes(X1, X2)) +
      geom_point(aes(color = value)) +
      scale_color_gradient2(midpoint = mp) +
      facet_wrap(~sex, nrow = 1) +
      theme_bw() +
      labs(x = "UMAP1", y = "UMAP2", 
           title = ifelse(.y == "bmi", "BMI", stringr::str_to_title(.y)), 
           color = NULL)
  }) %>%
  wrap_plots(ncol = 1)
```

```{r, fig.height=5, fig.width=15}
umap_embed %>%
  map2_dfr(strat_dat,
           inner_join,
           by = "eid",
           .id = "sex") %>%
  tidyr::pivot_longer(-c(X1, X2, sex, eid)) %>%
  mutate(name = toupper(name)) %>% #, 
  ggplot(aes(X1, X2)) +
  geom_point(aes(color = value)) +
  scale_color_gradient2(limits = c(-10, 10), low = scales::muted("blue"), high = scales::muted("red")) +
  facet_grid(sex ~ name) +
  theme_bw() +
  theme(panel.grid = element_blank(), legend.position = "top") +
  labs(x = NULL, y = NULL, color = "Value")
```

## Correlation between UMAP axes and input variables
```{r, fig.width=10, fig.height=7}
umap_embed %>%
  map2_dfr(strat_dat, inner_join, by = "eid", .id = "sex") %>%
  {
    d <- select(recoded_dat, eid, sex, age, smoking, bmi)
    inner_join(., d, by = c("eid", "sex"))
  } %>%
  tidyr::pivot_longer(-c(sex, eid, X1, X2)) %>%
  group_by(sex, name) %>%
  group_modify(~{ .x %>%
      with(data.frame(umap_axis = c("UMAP1", "UMAP2"),
                      Correlation = c(cor(X1, value), cor(X2, value))))
  }) %>%
  mutate(name = toupper(name)) %>%
  group_by(sex, umap_axis) %>%
  group_map(~{.x %>%
      ggplot(aes(Correlation, reorder(name, abs(Correlation)))) +
      geom_vline(xintercept = 0, lty = "dashed") +
      geom_segment(aes(xend = 0, yend = reorder(name, abs(Correlation)))) +
      geom_point(color = "red") +
      theme_bw() +
      labs(x = NULL, y = NULL, title = paste(.y$sex, "-", .y$umap_axis))
  }) %>%
  wrap_plots
```

## Archetypes
```{r, fig.width=11, fig.height=5}
load('../arch_mod.Rdata')
archdat <- arch_mod %>%
  map(~data.frame(.x$archetypes),
      .id = "sex")
arch_dict <- list(
    Female = tribble(
        ~archnum, ~archnam,
        1, "High HDL",
        2, "High FG",
        3, "Low BP",
        4, "High CRP",
        5, "Low WHR",
        6, "High BP",
        7, "High WHR",
        8, "High ALT",
        9, "High TG",
        10, "High LDL",
        11, "High SCR"
    ),
    Male = tribble(
        ~archnum, ~archnam,
        1, "High SCR",
        2, "High LDL",
        3, "High ALT",
        4, "High HDL",
        5, "High CRP",
        6, "High WHR",
        7, "High TG",
        8, "High BP",
        9, "High FG",
        10, "Low WHR"
    )
)

arch_labs <- archdat %>%
  imap(~{
    bind_cols(arch_dict[[.y]], .x)
  })
archdat_umap <- map(
    setNames(c("Female", "Male"), c("Female", "Male")),
    ~{
        d <- select(arch_labs[[.x]], -c(archnum, archnam))
        res <- umap_transform(d, umap_res[[.x]])
        res <- data.frame(res)
        bind_cols(select(arch_labs[[.x]], archnam), res)
    }
)

map(c("Female", "Male"),
    ~{umap_embed[[.x]] %>%
        ggplot(aes(X1, X2)) +
        geom_point(alpha = .1) +
        geom_point(data = archdat_umap[[.x]], aes(fill = archnam), shape = 23, size = 3) +
        theme_bw() +
        labs(x = "UMAP1", y = "UMAP2", title = .x, fill = "Archetypes")
    }) %>%
  wrap_plots(nrow = 1)


arch_alphas <- arch_mod %>%
  map2(arch_labs,
       ~{data.frame(.x$alphas) %>%
           setNames(.y$archnam)
        }) %>%
  map2(strat_dat,
       ~{.y %>%
           select(eid) %>%
           bind_cols(.x)
        })   



arch_alphas_long <- arch_alphas %>%
    map(~pivot_longer(.x, -eid))
```

